// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
module.exports = {
  addonType: "behavior",
  id: "skymen_parent_anchor",
  name: "Better Anchor",
  version: "1.0.0.2",
  category:
    // "attributes",
    // "movements",
    // "other",
    "general",
  author: "skymen",
  website: "https://www.construct.net",
  documentation: "https://www.construct.net",
  description: "Anchor object to parent or viewport with constraints",
  // icon: "icon.svg", // defaults to "icon.svg" if omitted
  // addonUrl: "https://www.construct.net/en/make-games/addons/####/XXXX", // displayed in auto-generated docs
  // githubUrl: "https://github.com/skymen/XXXX", // displays latest release version in auto-generated docs
  fileDependencies: [
    /*
    {
      filename: "filename.js", // no need to include "c3runtime/" prefix
      type:
        "copy-to-output"
        "inline-script"
        "external-dom-script"
        "external-runtime-script"
        "external-css"

      // for copy-to-output only
      // fileType: "image/png"
    }
    */
  ],
  info: {
    Set: {
      IsOnlyOneAllowed: true,
      CanBeBundled: true,
      IsDeprecated: false,
    },
  },
  properties: [
    /*
    {
      type:
        "integer"
        "float"
        "percent"
        "text"
        "longtext"
        "check"
        "font"
        "combo"
        "group"
        "link"
        "info"

      id: "property_id",
      options: {
        initialValue: 0,
        interpolatable: false,

        // minValue: 0, // omit to disable
        // maxValue: 100, // omit to disable

        // for type combo only
        // items: [
        //   {itemId1: "item name1" },
        //   {itemId2: "item name2" },
        // ],

        // dragSpeedMultiplier: 1, // omit to disable

        // for type link only
        // linkCallback: `function(instOrObj) {}`,
        // linkText: "Link Text",
        // callbackType:
        //   "for-each-instance"
        //   "once-for-type"

        // for type info only
        // infoCallback: `function(inst) {}`,
      },
      name: "Property Name",
      desc: "Property Description",
    }
    */
    {
      type: "combo",
      id: "resize_mode",
      options: {
        initialValue: "stretch",
        items: [
          { stretch: "Stretch" },
          { contain: "Contain" },
          { cover: "Cover" },
        ],
      },
      name: "Resize Mode",
      desc: "Resize Mode",
    },
    {
      type: "combo",
      id: "anchor_left",
      options: {
        initialValue: "left",
        items: [
          { left: "Left" },
          { center: "Center" },
          { right: "Right" },
          { none: "None" },
        ],
      },
      name: "Left Edge",
      desc: "Left Edge",
    },
    {
      type: "combo",
      id: "constraint_left",
      options: {
        initialValue: "absolute",
        items: [
          { absolute: "Absolute offset" },
          { percent: "Percentage" },
          { none: "No offset" },
        ],
      },
      name: "Left Constraint",
      desc: "Left Constraint",
    },
    {
      type: "combo",
      id: "anchor_top",
      options: {
        initialValue: "top",
        items: [
          { top: "Top" },
          { center: "Center" },
          { bottom: "Bottom" },
          { none: "None" },
        ],
      },
      name: "Top Edge",
      desc: "Top Edge",
    },
    {
      type: "combo",
      id: "constraint_top",
      options: {
        initialValue: "absolute",
        items: [
          { absolute: "Absolute offset" },
          { percent: "Percentage" },
          { none: "No offset" },
        ],
      },
      name: "Top Constraint",
      desc: "Top Constraint",
    },
    {
      type: "combo",
      id: "anchor_right",
      options: {
        initialValue: "none",
        items: [
          { left: "Left" },
          { center: "Center" },
          { right: "Right" },
          { none: "None" },
        ],
      },
      name: "Right Edge",
      desc: "Right Edge",
    },
    {
      type: "combo",
      id: "constraint_right",
      options: {
        initialValue: "absolute",
        items: [
          { absolute: "Absolute offset" },
          { percent: "Percentage" },
          { none: "No offset" },
        ],
      },
      name: "Right Constraint",
      desc: "Right Constraint",
    },
    {
      type: "combo",
      id: "anchor_bottom",
      options: {
        initialValue: "none",
        items: [
          { top: "Top" },
          { center: "Center" },
          { bottom: "Bottom" },
          { none: "None" },
        ],
      },
      name: "Bottom Edge",
      desc: "Bottom Edge",
    },
    {
      type: "combo",
      id: "constraint_bottom",
      options: {
        initialValue: "absolute",
        items: [
          { absolute: "Absolute offset" },
          { percent: "Percentage" },
          { none: "No offset" },
        ],
      },
      name: "Bottom Constraint",
      desc: "Bottom Constraint",
    },
    {
      type: "combo",
      id: "anchor_to",
      options: {
        initialValue: "parent",
        items: [{ parent: "Parent" }, { screen: "Viewport" }],
      },
      name: "Anchor To",
      desc: "Anchor To",
    },
    {
      type: "check",
      id: "enable",
      options: {
        initialValue: true,
      },
      name: "Enable",
      desc: "Enable",
    },
  ],
  aceCategories: {
    // follows the format id: langName
    // in the ACEs refer to categories using the id, not the name
    general: "General",
  },
  Acts: {
    /*
    SampleAction: {
      // The category of the action as it appears in the add action dialog
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this action
      // Cases where you might not want this are:
      // 1- If the action params are incompatible with the script interface
      // 2- If you don't want it to appear in the script interface
      // 3- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the action in the add action dialog
      highlight: true,

      // Set to true to hide the action in the interface. False by default if not specified.
      deprecated: false,

      // Marks the action as async. Defaults to false if not specified.
      isAsync: false,

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
            - "boolean"

            // The following types can take a default value but CANNOT be automatically generated in the script interface
            - "combo"

            // The following types CANNOT take a default value AND CANNOT be automatically generated in the script interface
            - "cmp"
            - "object"
            - "objectname"
            - "layer"
            - "layout"
            - "keyb"
            - "instancevar"
            - "instancevarbool"
            - "eventvar"
            - "eventvarbool"
            - "animation"
            - "objinstancevar"

          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          value: "the default value of the parameter",

          // Only for type "combo"
          items: [
            {"itemId1": "itemName1"},
            {"itemId2": "itemName2"},
            {"itemId3": "itemName3"},
          ],

          // Only for type "object"
          allowedPluginIds: ["Sprite", "TiledBg"],
        },
      ],

      // The name of the action as it appears in the add action dialog
      listName: "Sample Action",

      // The text that appears in the event sheet. Note, every single param must be used in the display text.
      // You can also use [b] and [i] tags.
      // You can also use the {my} tag to include the behavior icon and name.
      displayText: "{my}: Sample action [i]{0}[/i]",

      // The description of the action as it appears in the add action dialog
      description: "This is a sample action",
    },
    */
    SetEnabled: {
      category: "general",
      forward: "_SetEnabled",
      autoScriptInterface: true,
      params: [
        {
          id: "enabled",
          name: "Enabled",
          desc: "Enabled",
          type: "boolean",
          value: "true",
        },
      ],
      listName: "Set Enabled",
      displayText: "{my}: Set Enabled [i]{0}[/i]",
      description: "Set Enabled",
    },
    SetLeftOffset: {
      category: "general",
      forward: "_SetLeftOffset",
      autoScriptInterface: true,
      params: [
        {
          id: "offset",
          name: "Offset",
          desc: "Offset",
          type: "number",
          value: "0",
        },
        {
          id: "constraint",
          name: "Constraint",
          desc: "Constraint",
          type: "combo",
          items: [
            { absolute: "Absolute offset" },
            { percent: "Percentage" },
            { none: "No offset" },
          ],
          value: "absolute",
        },
      ],
      listName: "Set Left Offset",
      displayText: "{my}: Set Left Offset [i]{0}[/i] (Constraint: {1})",
      description: "Set Left Offset",
    },
    SetTopOffset: {
      category: "general",
      forward: "_SetTopOffset",
      autoScriptInterface: true,
      params: [
        {
          id: "offset",
          name: "Offset",
          desc: "Offset",
          type: "number",
          value: "0",
        },
        {
          id: "constraint",
          name: "Constraint",
          desc: "Constraint",
          type: "combo",
          items: [
            { absolute: "Absolute offset" },
            { percent: "Percentage" },
            { none: "No offset" },
          ],
          value: "absolute",
        },
      ],
      listName: "Set Top Offset",
      displayText: "{my}: Set Top Offset [i]{0}[/i] (Constraint: {1})",
      description: "Set Top Offset",
    },
    SetRightOffset: {
      category: "general",
      forward: "_SetRightOffset",
      autoScriptInterface: true,
      params: [
        {
          id: "offset",
          name: "Offset",
          desc: "Offset",
          type: "number",
          value: "0",
        },
        {
          id: "constraint",
          name: "Constraint",
          desc: "Constraint",
          type: "combo",
          items: [
            { absolute: "Absolute offset" },
            { percent: "Percentage" },
            { none: "No offset" },
          ],
          value: "absolute",
        },
      ],
      listName: "Set Right Offset",
      displayText: "{my}: Set Right Offset [i]{0}[/i] (Constraint: {1})",
      description: "Set Right Offset",
    },
    SetBottomOffset: {
      category: "general",
      forward: "_SetBottomOffset",
      autoScriptInterface: true,
      params: [
        {
          id: "offset",
          name: "Offset",
          desc: "Offset",
          type: "number",
          value: "0",
        },
        {
          id: "constraint",
          name: "Constraint",
          desc: "Constraint",
          type: "combo",
          items: [
            { absolute: "Absolute offset" },
            { percent: "Percentage" },
            { none: "No offset" },
          ],
          value: "absolute",
        },
      ],
      listName: "Set Bottom Offset",
      displayText: "{my}: Set Bottom Offset [i]{0}[/i] (Constraint: {1})",
      description: "Set Bottom Offset",
    },
    SetLeftEdge: {
      category: "general",
      forward: "_SetLeftEdge",
      autoScriptInterface: true,
      params: [
        {
          id: "edge",
          name: "Edge",
          desc: "Edge",
          type: "combo",
          items: [
            { left: "Left" },
            { center: "Center" },
            { right: "Right" },
            { none: "None" },
          ],
          value: "left",
        },
      ],
      listName: "Set Left Edge",
      displayText: "{my}: Set Left Edge [i]{0}[/i]",
      description: "Set Left Edge",
    },
    SetTopEdge: {
      category: "general",
      forward: "_SetTopEdge",
      autoScriptInterface: true,
      params: [
        {
          id: "edge",
          name: "Edge",
          desc: "Edge",
          type: "combo",
          items: [
            { top: "Top" },
            { center: "Center" },
            { bottom: "Bottom" },
            { none: "None" },
          ],
          value: "top",
        },
      ],
      listName: "Set Top Edge",
      displayText: "{my}: Set Top Edge [i]{0}[/i]",
      description: "Set Top Edge",
    },
    SetRightEdge: {
      category: "general",
      forward: "_SetRightEdge",
      autoScriptInterface: true,
      params: [
        {
          id: "edge",
          name: "Edge",
          desc: "Edge",
          type: "combo",
          items: [
            { left: "Left" },
            { center: "Center" },
            { right: "Right" },
            { none: "None" },
          ],
          value: "right",
        },
      ],
      listName: "Set Right Edge",
      displayText: "{my}: Set Right Edge [i]{0}[/i]",
      description: "Set Right Edge",
    },
    SetBottomEdge: {
      category: "general",
      forward: "_SetBottomEdge",
      autoScriptInterface: true,
      params: [
        {
          id: "edge",
          name: "Edge",
          desc: "Edge",
          type: "combo",
          items: [
            { top: "Top" },
            { center: "Center" },
            { bottom: "Bottom" },
            { none: "None" },
          ],
          value: "bottom",
        },
      ],
      listName: "Set Bottom Edge",
      displayText: "{my}: Set Bottom Edge [i]{0}[/i]",
      description: "Set Bottom Edge",
    },
    SetResizeMode: {
      category: "general",
      forward: "_SetResizeMode",
      autoScriptInterface: true,
      params: [
        {
          id: "mode",
          name: "Mode",
          desc: "Mode",
          type: "combo",
          items: [
            { stretch: "Stretch" },
            { contain: "Contain" },
            { cover: "Cover" },
          ],
          value: "stretch",
        },
      ],
      listName: "Set Resize Mode",
      displayText: "{my}: Set Resize Mode [i]{0}[/i]",
      description: "Set Resize Mode",
    },
    SetAnchorTo: {
      category: "general",
      forward: "_SetAnchorTo",
      autoScriptInterface: true,
      params: [
        {
          id: "anchor",
          name: "Anchor",
          desc: "Anchor",
          type: "combo",
          items: [{ parent: "Parent" }, { screen: "screen" }],
          value: "parent",
        },
      ],
      listName: "Set Anchor To",
      displayText: "{my}: Set Anchor To [i]{0}[/i]",
      description: "Set Anchor To",
    },
  },
  Cnds: {
    /*
    SampleCondition: {
      // The category of the action as it appears in the add condition dialog
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this condition
      // Cases where you might not want this are:
      // 1- If the condition params are incompatible with the script interface
      // 2- If you don't want it to appear in the script interface
      // 3- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the condition in the add condition dialog
      highlight: true,

      // Set to true to hide the condition in the interface. False by default if not specified.
      deprecated: false,

      // special conditions properties. These can all be omitted, and they will default to the following values:
      isTrigger: false,
      isFakeTrigger: false,
      isStatic: false,
      isLooping: false,
      isInvertible: true,
      isCompatibleWithTriggers: true,

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
            - "boolean"

            // The following types can take a default value but CANNOT be automatically generated in the script interface
            - "combo"

            // The following types CANNOT take a default value AND CANNOT be automatically generated in the script interface
            - "cmp"
            - "object"
            - "objectname"
            - "layer"
            - "layout"
            - "keyb"
            - "instancevar"
            - "instancevarbool"
            - "eventvar"
            - "eventvarbool"
            - "animation"
            - "objinstancevar"

          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          value: "the default value of the parameter",

          // Only for type "combo"
          items: [
            {"itemId1": "itemName1"},
            {"itemId2": "itemName2"},
            {"itemId3": "itemName3"},
          ],

          // Only for type "object"
          allowedPluginIds: ["Sprite", "TiledBg"],
        },
      ],

      // The name of the condition as it appears in the add condition dialog
      listName: "Sample Condition",

      // The text that appears in the event sheet. Note, every single param must be used in the display text.
      // You can also use [b] and [i] tags.
      // You can also use the {my} tag to include the behavior icon and name.
      displayText: "{my}: Sample condition [i]{0}[/i]",

      // The description of the condition as it appears in the add condition dialog
      description: "This is a sample condition",
    },
    */
    IsEnabled: {
      category: "general",
      forward: "_IsEnabled",
      autoScriptInterface: true,
      listName: "Is Enabled",
      displayText: "{my}: Is Enabled",
      description: "Is Enabled",
    },
  },
  Exps: {
    /*
    SampleExpression: {
      // The category of the action as it appears in the expression picker
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this expression
      // Cases where you might not want this are:
      // 1- If you don't want it to appear in the script interface
      // 2- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the expression in the expression picker
      highlight: true,

      // Set to true to hide the expression in the interface. False by default if not specified.
      deprecated: false,

      // The type of the expression.
      returnType:
        - "string"
        - "number"
        - "any" // must be either string or number

      // Set to true if the expression is variadic. False by default if not specified.
      isVariadicParameters: false

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
        },
      ],

      // The description of the expression as it appears in the expression picker
      description: "This is a sample expression",
    },
    */
    Left: {
      category: "general",
      forward: "_Left",
      autoScriptInterface: true,
      returnType: "number",
      listName: "Left",
      displayText: "{my}: Left",
      description: "Left",
    },
    Top: {
      category: "general",
      forward: "_Top",
      autoScriptInterface: true,
      returnType: "number",
      listName: "Top",
      displayText: "{my}: Top",
      description: "Top",
    },
    Right: {
      category: "general",
      forward: "_Right",
      autoScriptInterface: true,
      returnType: "number",
      listName: "Right",
      displayText: "{my}: Right",
      description: "Right",
    },
    Bottom: {
      category: "general",
      forward: "_Bottom",
      autoScriptInterface: true,
      returnType: "number",
      listName: "Bottom",
      displayText: "{my}: Bottom",
      description: "Bottom",
    },
  },
};
